"""Resolve and verify every reference in Appendix D against Crossref.

Chapter 10 of this book reports that a majority of citations generated by one
widely used model were entirely fabricated, and that fabricated references
characteristically pair real journal names with nonexistent titles. A reference
list in this book that contained one would be indefensible.

This script does not trust the list. For every entry it queries Crossref by
title, compares what comes back against what is claimed, and classifies the
result. It writes a report naming every entry that could not be confirmed.

    python tools/verify_references.py references.yaml

Exit code is non-zero if any entry is UNRESOLVED or MISMATCH, so it can run in
CI and fail a build rather than being read and forgotten.

Requires: httpx, pyyaml, rapidfuzz.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path

import httpx
import yaml
from rapidfuzz import fuzz

CROSSREF = "https://api.crossref.org/works"
MAILTO = "biotech.suryaprakash@gmail.com"   # polite pool, per Crossref etiquette
TITLE_MATCH_THRESHOLD = 88                  # below this, a human looks


@dataclass
class Result:
    ref_id: str
    claimed_title: str
    status: str          # CONFIRMED | MISMATCH | UNRESOLVED | SKIPPED
    doi: str | None
    found_title: str | None
    found_year: int | None
    claimed_year: int | None
    title_score: float | None
    note: str


def query_crossref(client: httpx.Client, title: str, year: int | None) -> dict | None:
    """Ask Crossref for the closest work by title. Returns the top item or None."""
    params = {
        "query.bibliographic": title,
        "rows": 5,
        "mailto": MAILTO,
    }
    if year:
        params["filter"] = f"from-pub-date:{year - 1}-01-01,until-pub-date:{year + 1}-12-31"

    try:
        r = client.get(CROSSREF, params=params, timeout=30.0)
        r.raise_for_status()
    except httpx.HTTPError as exc:
        print(f"    crossref error: {exc}", file=sys.stderr)
        return None

    items = r.json().get("message", {}).get("items", [])
    return items[0] if items else None


def year_of(item: dict) -> int | None:
    for key in ("published-print", "published-online", "issued", "created"):
        parts = item.get(key, {}).get("date-parts", [[None]])
        if parts and parts[0] and parts[0][0]:
            return int(parts[0][0])
    return None


def verify(entry: dict, client: httpx.Client) -> Result:
    ref_id = entry["id"]
    title = entry.get("title", "").strip()
    claimed_year = entry.get("year")

    # Standards, regulations and preprints without a Crossref record are
    # verified by URL rather than by DOI. Skipping them is a decision, not
    # an omission, so it is recorded as one.
    if entry.get("kind") in {"standard", "regulation", "documentation", "dataset"}:
        return Result(ref_id, title, "SKIPPED", entry.get("doi"), None, None,
                      claimed_year, None,
                      f"kind={entry['kind']}, verify by URL: {entry.get('url', 'none given')}")

    if not title:
        return Result(ref_id, title, "UNRESOLVED", None, None, None, claimed_year, None,
                      "no title in the entry to search on")

    item = query_crossref(client, title, claimed_year)
    if item is None:
        return Result(ref_id, title, "UNRESOLVED", None, None, None, claimed_year, None,
                      "no Crossref result")

    found_title = (item.get("title") or ["<none>"])[0]
    found_year = year_of(item)
    doi = item.get("DOI")
    score = fuzz.token_set_ratio(title.lower(), found_title.lower())

    notes = []
    if score < TITLE_MATCH_THRESHOLD:
        notes.append(f"title similarity {score:.0f} is below {TITLE_MATCH_THRESHOLD}")
    if claimed_year and found_year and abs(claimed_year - found_year) > 1:
        notes.append(f"year claimed {claimed_year}, Crossref says {found_year}")
    if entry.get("doi") and entry["doi"].lower() != (doi or "").lower():
        notes.append(f"DOI in the entry does not match Crossref: {entry['doi']} vs {doi}")

    status = "CONFIRMED" if not notes else "MISMATCH"
    return Result(ref_id, title, status, doi, found_title, found_year,
                  claimed_year, score, "; ".join(notes) or "matched")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("refs", type=Path, help="references.yaml")
    ap.add_argument("--out", type=Path, default=Path("references_report.md"))
    ap.add_argument("--json", type=Path, default=Path("references_resolved.json"))
    args = ap.parse_args()

    entries = yaml.safe_load(args.refs.read_text(encoding="utf-8"))["references"]
    results: list[Result] = []

    with httpx.Client(headers={"User-Agent": f"agentic-lab-refcheck ({MAILTO})"}) as client:
        for i, entry in enumerate(entries, 1):
            print(f"[{i}/{len(entries)}] {entry['id']}")
            results.append(verify(entry, client))
            time.sleep(0.4)      # Crossref asks for restraint; this is restraint

    counts = {}
    for r in results:
        counts[r.status] = counts.get(r.status, 0) + 1

    lines = ["# Reference verification report", ""]
    lines.append(f"Checked {len(results)} entries against Crossref.")
    lines.append("")
    for status in ("CONFIRMED", "MISMATCH", "UNRESOLVED", "SKIPPED"):
        lines.append(f"- {status}: {counts.get(status, 0)}")
    lines.append("")

    for status, heading in (
        ("MISMATCH", "Mismatches, which need a human"),
        ("UNRESOLVED", "Unresolved, which need a human"),
        ("SKIPPED", "Skipped by kind, verify by URL"),
        ("CONFIRMED", "Confirmed"),
    ):
        group = [r for r in results if r.status == status]
        if not group:
            continue
        lines.append(f"## {heading}")
        lines.append("")
        for r in group:
            lines.append(f"**{r.ref_id}**")
            lines.append(f"  claimed: {r.claimed_title}")
            if r.found_title:
                lines.append(f"  found:   {r.found_title}")
            if r.doi:
                lines.append(f"  doi:     {r.doi}")
            lines.append(f"  note:    {r.note}")
            lines.append("")

    args.out.write_text("\n".join(lines), encoding="utf-8")
    args.json.write_text(json.dumps([asdict(r) for r in results], indent=2),
                         encoding="utf-8")

    print(f"\nWrote {args.out} and {args.json}")
    for status in ("CONFIRMED", "MISMATCH", "UNRESOLVED", "SKIPPED"):
        print(f"  {status}: {counts.get(status, 0)}")

    bad = counts.get("MISMATCH", 0) + counts.get("UNRESOLVED", 0)
    if bad:
        print(f"\n{bad} entries need a human before this list can be printed.")
        return 1
    print("\nEvery entry confirmed or explicitly skipped.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
