"""Resolve and verify every reference in Appendix D against Crossref.

Chapter 10 of this book reports that a majority of citations generated by one
widely used model were entirely fabricated, and that fabricated references
characteristically pair real journal names with nonexistent titles. A reference
list in this book that contained one would be indefensible.

This script does not trust the list. For every entry it queries Crossref by
title, compares what comes back against what is claimed, and classifies the
result. It writes a report naming every entry that could not be confirmed.

    python tools/verify_references.py references.yaml

Exit code is non-zero if any entry is UNRESOLVED or MISMATCH, so it can run in
CI and fail a build rather than being read and forgotten.

Requires: httpx, pyyaml, rapidfuzz.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path

import httpx
import yaml
from rapidfuzz import fuzz

CROSSREF = "https://api.crossref.org/works"
MAILTO = "biotech.suryaprakash@gmail.com"   # polite pool, per Crossref etiquette
TITLE_MATCH_THRESHOLD = 88     # below this, a human looks
UNRESOLVED_FLOOR = 55          # below this, Crossref did not find it at all

# Crossref indexes far more than articles. A decision letter, a CRAN package
# record or a review wrapper can carry a title containing the claimed title
# in full, and token_set_ratio scores that 100. Filtering by type is what
# stops a wrong record being silently confirmed.
ACCEPT_TYPES = {
    "journal-article", "posted-content", "proceedings-article",
    "book", "book-chapter", "report", "monograph", "reference-entry",
}
REJECT_TITLE_PREFIXES = (
    "review for", "decision letter", "author response", "reviewer response",
    "correction to", "author correction", "publisher correction",
    "erratum", "retraction", "comment on", "reply to", "editorial expression",
)


@dataclass
class Result:
    ref_id: str
    claimed_title: str
    status: str          # CONFIRMED | MISMATCH | UNRESOLVED | UNSOURCED | SKIPPED
    doi: str | None
    found_title: str | None
    found_year: int | None
    claimed_year: int | None
    title_score: float | None
    note: str


def fetch_by_doi(client: httpx.Client, doi: str) -> dict | None:
    """Resolve a DOI directly. Always preferred over a title search.

    The first version of this script did not do this, and the consequence was
    worse than a missing feature: an entry carrying a correct, hand-verified
    DOI was searched by title, matched against an unrelated paper, and then
    failed on a DOI mismatch the tool had itself introduced. A verification
    tool that manufactures the error it reports is worse than no tool.
    """
    try:
        r = client.get(f"{CROSSREF}/{doi}", params={"mailto": MAILTO}, timeout=30.0)
        if r.status_code == 404:
            return None
        r.raise_for_status()
    except httpx.HTTPError as exc:
        print(f"    crossref DOI error: {exc}", file=sys.stderr)
        return None
    return r.json().get("message")


def query_crossref(client: httpx.Client, title: str, year: int | None) -> dict | None:
    """Ask Crossref for the closest work by title. Returns the top item or None."""
    params = {
        "query.bibliographic": title,
        "rows": 5,
        "mailto": MAILTO,
    }
    if year:
        params["filter"] = f"from-pub-date:{year - 1}-01-01,until-pub-date:{year + 1}-12-31"

    try:
        r = client.get(CROSSREF, params=params, timeout=30.0)
        r.raise_for_status()
    except httpx.HTTPError as exc:
        print(f"    crossref error: {exc}", file=sys.stderr)
        return None

    items = r.json().get("message", {}).get("items", [])
    for item in items:
        if acceptable(item):
            return item
    return None


def acceptable(item: dict) -> bool:
    """Is this Crossref record the kind of thing a reference can point at?

    Written after two entries were silently CONFIRMED against the wrong
    record: a JSS paper matched to its CRAN package, and an eLife article
    matched to the decision letter reviewing it. Both scored 100, because a
    claimed title that is a subset of a found title scores 100 under
    token_set_ratio. A wrong match reported as success is worse than a
    mismatch, because nothing flags it.
    """
    if item.get("type") not in ACCEPT_TYPES:
        return False
    title = (item.get("title") or [""])[0].lower().strip()
    return not title.startswith(REJECT_TITLE_PREFIXES)


def year_of(item: dict) -> int | None:
    for key in ("published-print", "published-online", "issued", "created"):
        parts = item.get(key, {}).get("date-parts", [[None]])
        if parts and parts[0] and parts[0][0]:
            return int(parts[0][0])
    return None


def verify(entry: dict, client: httpx.Client) -> Result:
    ref_id = entry["id"]
    title = entry.get("title", "").strip()
    claimed_year = entry.get("year")

    # Standards, regulations and preprints without a Crossref record are
    # verified by URL rather than by DOI. Skipping them is a decision, not
    # an omission, so it is recorded as one.
    if entry.get("kind") == "unsourced":
        return Result(ref_id, title, "UNSOURCED", None, None, None, claimed_year, None,
                      "This entry names a finding, not a work. It has no title, "
                      "author or venue that any tool can resolve. Source it or "
                      "remove the claim it supports.")

    # An arXiv preprint that Crossref does not index cannot be verified here,
    # and sending it to a title search produces a lexically similar paper on
    # the same topic and calls it a mismatch. Two papers about multi-agent
    # scientific discovery share most of their content words because they are
    # about the same thing; no string metric separates them, and raising the
    # floor far enough to try would discard genuine near-matches. Verify these
    # by arXiv ID instead, and record that as a decision.
    if entry.get("kind") == "preprint" and entry.get("arxiv"):
        return Result(ref_id, title, "SKIPPED", None, None, None, claimed_year, None,
                      f"arXiv preprint, verify at arxiv.org/abs/{entry['arxiv']}")

    if entry.get("kind") in {"standard", "regulation", "documentation", "dataset"}:
        return Result(ref_id, title, "SKIPPED", entry.get("doi"), None, None,
                      claimed_year, None,
                      f"kind={entry['kind']}, verify by URL: {entry.get('url', 'none given')}")

    if not title:
        return Result(ref_id, title, "UNRESOLVED", None, None, None, claimed_year, None,
                      "no title in the entry to search on")

    # An entry carrying a DOI is resolved by that DOI, never by title search.
    by_doi = False
    item = None
    if entry.get("doi"):
        item = fetch_by_doi(client, entry["doi"])
        by_doi = item is not None
        if item is None:
            return Result(ref_id, title, "MISMATCH", entry["doi"], None, None,
                          claimed_year, None,
                          "the DOI in this entry does not resolve at Crossref")

    if item is None:
        item = query_crossref(client, title, claimed_year)

    if item is None:
        return Result(ref_id, title, "UNRESOLVED", None, None, None, claimed_year, None,
                      "no Crossref result")

    found_title = (item.get("title") or ["<none>"])[0]
    found_year = year_of(item)
    doi = item.get("DOI")
    # token_sort_ratio is symmetric: it will not score 100 merely because the
    # claimed title is contained within a longer found title. token_set_ratio
    # is kept for diagnosis only, because a large gap between the two is
    # itself the signal that one title contains the other.
    score = fuzz.token_sort_ratio(title.lower(), found_title.lower())
    containment = fuzz.token_set_ratio(title.lower(), found_title.lower())

    # A title search returning something barely related has not found the work.
    # Reporting that as a mismatch blames the entry for the tool's failure to
    # find it, which is what arXiv preprints Crossref does not hold produced in
    # the first run. Below the floor, the honest verdict is UNRESOLVED.
    if not by_doi and score < UNRESOLVED_FLOOR:
        hint = ""
        if entry.get("arxiv"):
            hint = f" Verify by arXiv ID {entry['arxiv']} instead."
        elif entry.get("kind") == "preprint":
            hint = " Preprints are often absent from Crossref; verify at the server."
        return Result(ref_id, title, "UNRESOLVED", None, found_title, found_year,
                      claimed_year, score,
                      f"best Crossref hit scored {score:.0f}, below the floor of "
                      f"{UNRESOLVED_FLOOR}, so nothing matching was found.{hint}")

    notes = []
    if containment - score > 25:
        notes.append(
            f"the claimed title appears to be contained in a longer found "
            f"title (containment {containment:.0f} against similarity "
            f"{score:.0f}); check this is the work and not a wrapper record")
    if score < TITLE_MATCH_THRESHOLD:
        notes.append(f"title similarity {score:.0f} is below {TITLE_MATCH_THRESHOLD}")
    if claimed_year and found_year and abs(claimed_year - found_year) > 1:
        notes.append(f"year claimed {claimed_year}, Crossref says {found_year}")
    if entry.get("doi") and not by_doi and entry["doi"].lower() != (doi or "").lower():
        notes.append(f"DOI in the entry does not match the title search result: "
                     f"{entry['doi']} vs {doi}")

    status = "CONFIRMED" if not notes else "MISMATCH"
    how = "resolved by DOI" if by_doi else "matched by title search"
    return Result(ref_id, title, status, doi, found_title, found_year,
                  claimed_year, score, "; ".join(notes) or how)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("refs", type=Path, help="references.yaml")
    ap.add_argument("--out", type=Path, default=Path("references_report.md"))
    ap.add_argument("--json", type=Path, default=Path("references_resolved.json"))
    args = ap.parse_args()

    entries = yaml.safe_load(args.refs.read_text(encoding="utf-8"))["references"]
    results: list[Result] = []

    with httpx.Client(headers={"User-Agent": f"agentic-lab-refcheck ({MAILTO})"}) as client:
        for i, entry in enumerate(entries, 1):
            print(f"[{i}/{len(entries)}] {entry['id']}")
            results.append(verify(entry, client))
            time.sleep(0.4)      # Crossref asks for restraint; this is restraint

    counts = {}
    for r in results:
        counts[r.status] = counts.get(r.status, 0) + 1

    lines = ["# Reference verification report", ""]
    by_doi_count = sum(1 for r in results
                       if r.status == "CONFIRMED" and "by DOI" in r.note)
    confirmed = sum(1 for r in results if r.status == "CONFIRMED")
    lines.append(f"Checked {len(results)} entries against Crossref.")
    lines.append("")
    lines.append(
        f"Of {confirmed} confirmations, {by_doi_count} were resolved by DOI and "
        f"{confirmed - by_doi_count} by title search. A DOI is checked; a title "
        f"match is inferred. Adding a DOI to an entry is the single highest "
        f"value change available here, and it is safe to add one from any "
        f"source, because this script resolves it and will report a mismatch "
        f"if it is wrong.")
    lines.append("")
    for status in ("CONFIRMED", "MISMATCH", "UNRESOLVED", "UNSOURCED", "SKIPPED"):
        lines.append(f"- {status}: {counts.get(status, 0)}")
    lines.append("")

    for status, heading in (
        ("UNSOURCED", "Unsourced, which need a source or a softened claim"),
        ("MISMATCH", "Mismatches, which need a human"),
        ("UNRESOLVED", "Unresolved, which need a human"),
        ("SKIPPED", "Skipped by kind, verify by URL"),
        ("CONFIRMED", "Confirmed"),
    ):
        group = [r for r in results if r.status == status]
        if not group:
            continue
        lines.append(f"## {heading}")
        lines.append("")
        for r in group:
            lines.append(f"**{r.ref_id}**")
            lines.append(f"  claimed: {r.claimed_title}")
            if r.found_title:
                lines.append(f"  found:   {r.found_title}")
            if r.doi:
                lines.append(f"  doi:     {r.doi}")
            lines.append(f"  note:    {r.note}")
            lines.append("")

    args.out.write_text("\n".join(lines), encoding="utf-8")
    args.json.write_text(json.dumps([asdict(r) for r in results], indent=2),
                         encoding="utf-8")

    print(f"\nWrote {args.out} and {args.json}")
    for status in ("CONFIRMED", "MISMATCH", "UNRESOLVED", "UNSOURCED", "SKIPPED"):
        print(f"  {status}: {counts.get(status, 0)}")

    bad = (counts.get("MISMATCH", 0) + counts.get("UNRESOLVED", 0)
           + counts.get("UNSOURCED", 0))
    if bad:
        print(f"\n{bad} entries need a human before this list can be printed.")
        return 1
    print("\nEvery entry confirmed or explicitly skipped.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
